### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/express-favicon-short-circuit#1]
if you have got 5' and would like to have a look at this npm package I just published I'd really love to have your opinion on it 😄 thanks!

// cc @nickbalestra @chriscartlidge @munkychop @tpgmartin @matteofigus

**Comment by nickbalestra** [comment]
I wonder if so, the browser will keep requesting it on each page req...?  In that case simply relying on express/serve-favicon could be a better solution (once client got it cached should stop requesting, no?)

**Comment by mattiaerre** [comment]
thank you very much for your feedback @nickbalestra as per my knowledge:
- the browser will request the fake favicon the same way it will request a "real" one; ~~no issue from a caching POV (and you can test it yourself w/ `npm run example`)~~ but I had a look at the example and you are right it looks like the browser is requesting it every time ... need to investigate more
- of course using express/serve-favicon is a better approach but I see the usage of my module while still in development/app prototyping (if you know what I mean)

the other day @chriscartlidge and I spotted a weird error when we were server side rendering a .pug view and we couldn't figured it out what it was. It turned out the 500 was generated by that little b***h ... 😄

**Comment by mattiaerre** [comment]
Hi @kentbrew since this express middleware is based on your original code (see README.md), it would be nice if you can cast an eye over it as well. Thank you very much!

**Comment by mattiaerre** [comment]
hi @nickbalestra I just released a new version that returns 301 http status code instead of 200 and it looks like now the browser is able to cache it (see attached screenshot)

![screen shot 2016-08-25 at 10 21 30](https://cloud.githubusercontent.com/assets/6423261/17963490/bba7595c-6aad-11e6-8767-62d134e6158f.png)

thanks for this 😉

**Comment by mattiaerre** [comment]
no feedback from @chriscartlidge @munkychop @tpgmartin @matteofigus so I am going to close this issue 😅

**Comment by munkychop** [comment]
@mattiaerre hey sorry, I didn't get a chance to look at this and until now. All looks good to me 👍

**Comment by mattiaerre** [comment]
thank you very much @munkychop see you later!
